[tool.pytest.ini_options]
markers = [
    "integration: test requires access to an external resource",
    "slow: these tests take FOREVER",
    "mpi: these tests are mpi-enabled"
]
addopts = "-s"

[tool.mypy]
disallow_untyped_defs = true
#ignore_missing_imports = true
